-- Q1. What is the total revenue generated by male vs. female customers?
select 
	gender, sum(purchase_amount) as revenue from clean_retail_data
    group by gender;
    
-- Q2. Which customers used a discount but still spent more than the average purchase amount?

select
	customer_id, discount_applied, purchase_amount from clean_retail_data 
    where discount_applied = "Yes" and purchase_amount > (select avg(purchase_amount) as avg_amount from clean_retail_data )
    order by purchase_amount desc;
    
-- Q3. Which are the top 5 products with the highest average review rating?

select 
	item_purchased, round(avg(review_rating),2) as avg_review_rating from clean_retail_data
	group by item_purchased order by avg_review_rating desc limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select
	shipping_type, round(avg(purchase_amount),2) as avg_purchase from clean_retail_data
    where shipping_type in ("Standard" , "Express")
    group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select
	subscription_status, round(avg(purchase_amount),2) as spend, sum(purchase_amount) as revenue from clean_retail_data
    group by subscription_status order by revenue, spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select
	item_purchased,
    round(sum(
    case
		when discount_applied = "Yes" then 1
        else 0
	end)/count(*)*100,2) as filter_row
	from clean_retail_data
    group by item_purchased order by filter_row desc limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 

with customer_type as( 
select
	customer_id, previous_purchases, gender,
	case
		when previous_purchases = 1 then "New"
        when previous_purchases between 2 and 10 then "Returning"
        else "Loyal"
    end as segment
	from clean_retail_data)
select segment, gender, count(customer_id) as count from customer_type
group by segment, gender order by count asc    
;
    

-- Q8. What are the top 3 most purchased products within each category?
with top_product_catg as (
select
	item_purchased, category, count(customer_id) as count,
    row_number() over(partition by category order by count(customer_id) desc) as rating_rank
    from clean_retail_data group by category, item_purchased)
select category, item_purchased, rating_rank from top_product_catg
where rating_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select
	subscription_status, count(customer_id) as count from clean_retail_data
    where previous_purchases > 5
    group by subscription_status;

-- Q10. What is the revenue contribution of each age group? 

select
	age_group, sum(purchase_amount) as revenue from clean_retail_data
    group by age_group;

















